apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment-1
  labels:
    app: iperf-server-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server-1
  template:
    metadata:
      labels:
        app: iperf-server-1
        node: {NODE}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {NODE}
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ['-s', '-p', '5300', '-A', '16']
        ports:
        - containerPort: 5001
          name: server
      terminationGracePeriodSeconds: 0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment-2
  labels:
    app: iperf-server-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server-2
  template:
    metadata:
      labels:
        app: iperf-server-2
        node: {NODE}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {NODE}
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ['-s', '-p', '5301', '-A', '17']
        ports:
        - containerPort: 5001
          name: server
      terminationGracePeriodSeconds: 0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment-3
  labels:
    app: iperf-server-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server-3
  template:
    metadata:
      labels:
        app: iperf-server-3
        node: {NODE}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {NODE}
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ['-s', '-p', '5302', '-A', '18']
        ports:
        - containerPort: 5001
          name: server
      terminationGracePeriodSeconds: 0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment-4
  labels:
    app: iperf-server-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server-4
  template:
    metadata:
      labels:
        app: iperf-server-4
        node: {NODE}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {NODE}
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ['-s', '-p', '5303', '-A', '19']
        ports:
        - containerPort: 5001
          name: server
      terminationGracePeriodSeconds: 0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment-5
  labels:
    app: iperf-server-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server-5
  template:
    metadata:
      labels:
        app: iperf-server-5
        node: {NODE}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {NODE}
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ['-s', '-p', '5304', '-A', '20']
        ports:
        - containerPort: 5001
          name: server
      terminationGracePeriodSeconds: 0

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment-6
  labels:
    app: iperf-server-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server-6
  template:
    metadata:
      labels:
        app: iperf-server-6
        node: {NODE}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - {NODE}
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
      - name: iperf3-server
        image: networkstatic/iperf3
        args: ['-s', '-p', '5305', '-A', '21']
        ports:
        - containerPort: 5001
          name: server
      terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-1
  labels:
    app: iperf-client-1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - {NODE}
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  containers:
  - name: iperf-client
    image: networkstatic/iperf3
    command: ['/bin/sh', '-c', 'sleep 1d']
  terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-2
  labels:
    app: iperf-client-2
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - {NODE}
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  containers:
  - name: iperf-client
    image: networkstatic/iperf3
    command: ['/bin/sh', '-c', 'sleep 1d']
  terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-3
  labels:
    app: iperf-client-3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - {NODE}
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  containers:
  - name: iperf-client
    image: networkstatic/iperf3
    command: ['/bin/sh', '-c', 'sleep 1d']
  terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-4
  labels:
    app: iperf-client-4
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - {NODE}
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  containers:
  - name: iperf-client
    image: networkstatic/iperf3
    command: ['/bin/sh', '-c', 'sleep 1d']
  terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-5
  labels:
    app: iperf-client-5
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - {NODE}
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  containers:
  - name: iperf-client
    image: networkstatic/iperf3
    command: ['/bin/sh', '-c', 'sleep 1d']
  terminationGracePeriodSeconds: 0

---

apiVersion: v1
kind: Pod
metadata:
  name: iperf-client-6
  labels:
    app: iperf-client-6
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
            - {NODE}
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  containers:
  - name: iperf-client
    image: networkstatic/iperf3
    command: ['/bin/sh', '-c', 'sleep 1d']
  terminationGracePeriodSeconds: 0